// <auto-generated />
using System;
using IncomeTaxCalculator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncomeTaxCalculator.Infrastructure.Migrations
{
    [DbContext(typeof(IncomeTaxCalculatorContext))]
    partial class IncomeTaxCalculatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("IncomeTaxCalculator.Domain.Entities.Aggregates.Taxes.TaxBand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LowerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.Property<int>("TaxSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpperLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaxSystemId");

                    b.ToTable("TaxBand");
                });

            modelBuilder.Entity("IncomeTaxCalculator.Domain.Entities.Aggregates.Taxes.TaxSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaxSystem");
                });

            modelBuilder.Entity("IncomeTaxCalculator.Domain.Entities.Aggregates.Taxes.TaxBand", b =>
                {
                    b.HasOne("IncomeTaxCalculator.Domain.Entities.Aggregates.Taxes.TaxSystem", "TaxSystem")
                        .WithMany("Bands")
                        .HasForeignKey("TaxSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxSystem");
                });

            modelBuilder.Entity("IncomeTaxCalculator.Domain.Entities.Aggregates.Taxes.TaxSystem", b =>
                {
                    b.Navigation("Bands");
                });
#pragma warning restore 612, 618
        }
    }
}
